### ISSUE TITLE
current code does not compile

### ISSUE THREAD

**Issue by eduyayo** [william-reed/Lode-Scape#1]
Hi, 
Got several compilation errors in current version.
Coul´d you take a look into them?

**Comment by william-reed** [comment]
The code compiled under the older version of LibGDX at the time of upload which was about 3 years ago now. I don't have plans on updating this particular repository due to the sloppy nature of the project's code and my lack of understanding of a bigger picture at the time of this program's development. It would essentially require a complete rewrite for me to be happy with the code. If there are errors in compilation it should only be because of the new LibGDX that is available which should be minor things to change

**Comment by eduyayo** [comment]
mh... I did not update the lbraries and have added those contained in the project to the classpath, it did not work...

**Comment by william-reed** [comment]
Posting a stack trace could help me if it is not a libGDX problem

**Comment by eduyayo** [comment]
Crafting.java:50 "Cannot make a static reference to the non-static field ArrayListsz.amountOfTrees"

look like not all the code is commited

**Comment by william-reed** [comment]
It makes me cringe that I ever even attempted to use a static integer in such a way, but it should be simple to fix. I am guessing the int should not be final and should be static (if keeping with this poor code design and implementation). Feel free to submit a pull request

**Comment by eduyayo** [comment]
there are more and more like that, missing methods and constructors something I don´t remember right now. 
it renders code useless for a newcomer :(

**Comment by william-reed** [comment]
Having been several years since compiling this code, I am honestly not sure why these errors are even coming up. I don't know why I would have pushed the code if such errors existed. 

I don't see how it renders the code useless though. 

Either way I would definitely not recommend looking at this code regardless of the reason due to everything wrong with it.
